# This is a basic workflow to help you get started with Actions

name: main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_spfx:
    # The type of runner that the job will run on
    uses: saif-Sb/DevopsTest/.github/workflows/build-spfx.yml@main
  deploy_spfx_uat:
    needs: build_spfx
    uses: saif-Sb/DevopsTest/.github/workflows/deploy-spfx-pnp-powershell.yml@main 
    with:
      environment_name: UAT
      spfx_package_name: "${{ needs.build_spfx.outputs.package_name }}"
      site_url_prd: https://saifneos.sharepoint.com/sites/PRD
      site_list_prd: Lists/Employee
      site_name_prd: CommSite
      site_copy_owner: saifneos@saifneos.onmicrosoft.com
      webpart_name: HelloDevops
    secrets:
      AAD_APP_ID: ${{ secrets.AAD_APP_ID }}
      AAD_APP_PASSWORD: ${{ secrets.AAD_APP_PASSWORD }}
      AAD_APP_ENCODED_CERTIFICATE: ${{ secrets.AAD_APP_ENCODED_CERTIFICATE }}
      AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}
      
  deploy_spfx_prd:
    needs: deploy_spfx_uat
    uses: saif-Sb/DevopsTest/.github/workflows/deploy-spfx-pnp-powershell.yml@main
    with:
      environment_name: PRD
      spfx_package_name: "${{ needs.deploy_spfx_uat.outputs.sharepoint_package }}"
      site_url_prd: https://saifneos.sharepoint.com/sites/PRD
      site_to_remove: "${{ needs.deploy_spfx_uat.outputs.site_to_remove }}"
      app_catalog_site_url: https://saifneos.sharepoint.com/sites/AppCatalog
      app_catalog_scope: tenant
    secrets:
      AAD_APP_ID: ${{ secrets.AAD_APP_ID }}
      AAD_APP_PASSWORD: ${{ secrets.AAD_APP_PASSWORD }}
      AAD_APP_ENCODED_CERTIFICATE: ${{ secrets.AAD_APP_ENCODED_CERTIFICATE }}
      AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}
